name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build and Deploy Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build --prod
        npx netlify deploy --prod --dir=dist/frontend --auth=$NETLIFY_AUTH_TOKEN

    - name: Deploy Backend to Render
      working-directory: ./backend
      run: |
        npm install
        render-cli deploy