version: '3.8'

services:
  frontend:
    build:
      context: ./client/final-project  # Asegúrate de que esta ruta sea correcta
    ports:
      - "4200:4200"  # Asegúrate de mapear correctamente el puerto 4200
    networks:
      - red-clinica

  backend:
    build:
      context: ./server
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/final-project-db
    depends_on:
      - mongo
    networks:
      - red-clinica
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - red-clinica

networks:
  red-clinica:

volumes:
  mongo-data:
